### ISSUE TITLE
Table relations not generated

### ISSUE THREAD

**Issue by pitzzahh** [L-Mario564/drizzle-dbml-generator#17]
Hi. It generated the dbml and the svg output, however the relations are not present.

I have my schema per file and merged them in an index.ts, does it work with this? or does it need to be in a single schema file?

- src/lib/server/db/schema/
 `.
├── absences.ts
├── appointmentInformation.ts
├── archive.ts
├── archiveType.ts
├── authHistory.ts
├── authType.ts
├── bankAccount.ts
├── civilStatus.ts
├── employeeSalary.ts
├── employee.ts
├── employmentStatus.ts
├── gender.ts
├── gsis.ts
├── index.ts
├── organization.ts
├── passwordResetToken.ts
├── position.ts
├── role.ts
├── salaryGrade.ts
├── salary.ts
├── session.ts
├── station.ts
├── status.ts
├── tax.ts
├── userPreference.ts
├── userStatus.ts
└── user.ts

1 directory, 27 files
` 
- src/lib/db/index.ts
```ts 
import { drizzle } from 'drizzle-orm/node-postgres';
import * as schema from '@/server/db/schema';
import pg from 'pg';
import { pgGenerate } from 'drizzle-dbml-generator';

export const pool = new pg.Pool({
	connectionString: process.env.DATABASE_URL
});

const db = drizzle(pool, { schema });
const out = './schema.dbml';
const relational = true;

console.info(pgGenerate({ schema, out, relational }));

export default db;
```

```bash
"dbml:generate": "bun run -r dotenv/config src/lib/server/db/index.ts && bun dbml:render",
"dbml:render": "bun dbml-renderer -i schema.dbml -o erd.svg"
```

**Comment by L-Mario564** [comment]
The way you have it set up should work. Can you show me a snippet where I can see how you're defining relations?

**Comment by pitzzahh** [comment]
> The way you have it set up should work. Can you show me a snippet where I can see how you're defining relations?

Hi, thanks for the response. It works now, it was my fault that I did not include the relations as an export. I thought it works out of the box. I now created a sub directory containing the table relations and it now generates it properly.

**Comment by pitzzahh** [comment]
```js
import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { employee } from '.';
import { createId } from '@paralleldrive/cuid2';

const appointmentInformation = pgTable('appointment_info', {
        id: text('id')
                .primaryKey()
                .$defaultFn(() => createId()),
        createdAt: timestamp('created_at', { precision: 3 }).defaultNow(),
        updatedAt: timestamp('updated_at', { precision: 3 }).$onUpdate(() => new Date()),
        appointmentDate: timestamp('appointment_date', { precision: 3 }).notNull(),
        lastPromotionDate: timestamp('last_promotion', { precision: 3 }).notNull(),
        employeeId: text('employee_id').notNull()
});

export const appointmentStatusRelations = relations(appointmentInformation, ({ one }) => {
        return {
                employee: one(employee, {
                        fields: [appointmentInformation.employeeId],
                        references: [employee.id]
                })
        };
});

export default appointmentInformation;
```

**Comment by pitzzahh** [comment]
> ```js
> import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
> import { relations } from 'drizzle-orm';
> import { employee } from '.';
> import { createId } from '@paralleldrive/cuid2';
> 
> const appointmentInformation = pgTable('appointment_info', {
>         id: text('id')
>                 .primaryKey()
>                 .$defaultFn(() => createId()),
>         createdAt: timestamp('created_at', { precision: 3 }).defaultNow(),
>         updatedAt: timestamp('updated_at', { precision: 3 }).$onUpdate(() => new Date()),
>         appointmentDate: timestamp('appointment_date', { precision: 3 }).notNull(),
>         lastPromotionDate: timestamp('last_promotion', { precision: 3 }).notNull(),
>         employeeId: text('employee_id').notNull()
> });
> 
> export const appointmentStatusRelations = relations(appointmentInformation, ({ one }) => {
>         return {
>                 employee: one(employee, {
>                         fields: [appointmentInformation.employeeId],
>                         references: [employee.id]
>                 })
>         };
> });
> 
> export default appointmentInformation;
> ```

this was fixed by separating the relations to a new file.
