### ISSUE TITLE
No table definition generated

### ISSUE THREAD

**Issue by leoraba** [L-Mario564/drizzle-dbml-generator#21]
Hi, I just updated to latest versions of drizzle-dbml-generator + Drizzle + pg and it stopped generating tables definitions on my dbml file, it generates a dbml file only with refs and enums definitions but not tables.

Not working dependencies:
```
"drizzle-dbml-generator": "^0.7.0"
"drizzle-kit": "^0.23.0"
"drizzle-orm": "^0.32.0"
"pg": "^8.12.0"
```

dbml generation works fine using this dependencies:
```
"drizzle-dbml-generator": "^0.6.1"
"drizzle-kit": "^0.20.18"
"drizzle-orm": "^0.29.5"
"pg": "^8.12.0"
```

Tested using node v20.

**Comment by L-Mario564** [comment]
Fixed in latest release.
