### ISSUE TITLE
Does it work with multiple schema files?

### ISSUE THREAD

**Issue by marvkr** [L-Mario564/drizzle-dbml-generator#3]
How does it work when schemas are not all in one schemas.ts file but broken down like this? : 

📦 <project root>
 └ 📂 src
    └ 📂 db
       └ 📂 schema
          ├ 📜 users.ts
          ├ 📜 countries.ts
          ├ 📜 cities.ts
          ├ 📜 products.ts
          ├ 📜 clients.ts
          ├ 📜 enums.ts
          └ 📜 etc.ts

**Comment by L-Mario564** [comment]
You can make an `index.ts` file inside `schema` and re-export everything there. So, following your example:

```ts
// schema/index.ts
export * from './users';
export * from './countries';
export * from './cities';
export * from './products';
export * from './clients';
export * from './enums';
export * from './etc';
```

And then in the script you use to generate it you can import it as normal:

```ts
import * as schema from './schema';
```
