### ISSUE TITLE
Support stdout

### ISSUE THREAD

**Issue by cometkim** [L-Mario564/drizzle-dbml-generator#8]
I wanna emit dbml to just stdout, and redirect it to other place

Perhaps making it as default behavior is more sensible. And `--file $path` as an option (which is useful some cases, but POSIX-style redirection is simpler)

**Comment by L-Mario564** [comment]
What's your use case for such functionality?

**Comment by cometkim** [comment]
I want to decide the output path in the exexution context, not in the script.

`node generate.js > out.dbml`

**Comment by L-Mario564** [comment]
I can make it so it returns a string and then you're able to manipulate it however you'd like to.
